<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF2ok2Dz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF2ok2Dz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF2ok2Dz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF2ok2Dz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF2ok2Dz\App_KernelDevDebugContainer([
    'container.build_hash' => 'F2ok2Dz',
    'container.build_id' => '75ab443c',
    'container.build_time' => 1590148573,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF2ok2Dz');
